# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/oragon/ws/banjo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/oragon/ws/banjo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oragon/ws/banjo/CMakeFiles /home/oragon/ws/banjo//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oragon/ws/banjo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/oragon/ws/banjo/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named banjo

# Build rule for target.
banjo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 banjo
.PHONY : banjo

# fast build rule for target.
banjo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/build
.PHONY : banjo/fast

#=============================================================================
# Target rules for targets named assert

# Build rule for target.
assert: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 assert
.PHONY : assert

# fast build rule for target.
assert/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/assert.dir/build.make examples/CMakeFiles/assert.dir/build
.PHONY : assert/fast

#=============================================================================
# Target rules for targets named audio_pcm

# Build rule for target.
audio_pcm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 audio_pcm
.PHONY : audio_pcm

# fast build rule for target.
audio_pcm/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/audio_pcm.dir/build.make examples/CMakeFiles/audio_pcm.dir/build
.PHONY : audio_pcm/fast

#=============================================================================
# Target rules for targets named bitmap_blit

# Build rule for target.
bitmap_blit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bitmap_blit
.PHONY : bitmap_blit

# fast build rule for target.
bitmap_blit/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/bitmap_blit.dir/build.make examples/CMakeFiles/bitmap_blit.dir/build
.PHONY : bitmap_blit/fast

#=============================================================================
# Target rules for targets named build_info

# Build rule for target.
build_info: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_info
.PHONY : build_info

# fast build rule for target.
build_info/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/build_info.dir/build.make examples/CMakeFiles/build_info.dir/build
.PHONY : build_info/fast

#=============================================================================
# Target rules for targets named drawing_2d

# Build rule for target.
drawing_2d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 drawing_2d
.PHONY : drawing_2d

# fast build rule for target.
drawing_2d/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/drawing_2d.dir/build.make examples/CMakeFiles/drawing_2d.dir/build
.PHONY : drawing_2d/fast

#=============================================================================
# Target rules for targets named drawing_text

# Build rule for target.
drawing_text: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 drawing_text
.PHONY : drawing_text

# fast build rule for target.
drawing_text/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/drawing_text.dir/build.make examples/CMakeFiles/drawing_text.dir/build
.PHONY : drawing_text/fast

#=============================================================================
# Target rules for targets named event_callbacks

# Build rule for target.
event_callbacks: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 event_callbacks
.PHONY : event_callbacks

# fast build rule for target.
event_callbacks/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/event_callbacks.dir/build.make examples/CMakeFiles/event_callbacks.dir/build
.PHONY : event_callbacks/fast

#=============================================================================
# Target rules for targets named event_polling

# Build rule for target.
event_polling: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 event_polling
.PHONY : event_polling

# fast build rule for target.
event_polling/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/event_polling.dir/build.make examples/CMakeFiles/event_polling.dir/build
.PHONY : event_polling/fast

#=============================================================================
# Target rules for targets named handling_errors

# Build rule for target.
handling_errors: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 handling_errors
.PHONY : handling_errors

# fast build rule for target.
handling_errors/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/handling_errors.dir/build.make examples/CMakeFiles/handling_errors.dir/build
.PHONY : handling_errors/fast

#=============================================================================
# Target rules for targets named load_bmp

# Build rule for target.
load_bmp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 load_bmp
.PHONY : load_bmp

# fast build rule for target.
load_bmp/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/load_bmp.dir/build.make examples/CMakeFiles/load_bmp.dir/build
.PHONY : load_bmp/fast

#=============================================================================
# Target rules for targets named logging

# Build rule for target.
logging: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 logging
.PHONY : logging

# fast build rule for target.
logging/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/logging.dir/build.make examples/CMakeFiles/logging.dir/build
.PHONY : logging/fast

#=============================================================================
# Target rules for targets named memory_callbacks

# Build rule for target.
memory_callbacks: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 memory_callbacks
.PHONY : memory_callbacks

# fast build rule for target.
memory_callbacks/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/memory_callbacks.dir/build.make examples/CMakeFiles/memory_callbacks.dir/build
.PHONY : memory_callbacks/fast

#=============================================================================
# Target rules for targets named pixel_mode

# Build rule for target.
pixel_mode: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pixel_mode
.PHONY : pixel_mode

# fast build rule for target.
pixel_mode/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/pixel_mode.dir/build.make examples/CMakeFiles/pixel_mode.dir/build
.PHONY : pixel_mode/fast

#=============================================================================
# Target rules for targets named shaders

# Build rule for target.
shaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shaders
.PHONY : shaders

# fast build rule for target.
shaders/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/shaders.dir/build.make examples/CMakeFiles/shaders.dir/build
.PHONY : shaders/fast

#=============================================================================
# Target rules for targets named sprite_animation

# Build rule for target.
sprite_animation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sprite_animation
.PHONY : sprite_animation

# fast build rule for target.
sprite_animation/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/sprite_animation.dir/build.make examples/CMakeFiles/sprite_animation.dir/build
.PHONY : sprite_animation/fast

#=============================================================================
# Target rules for targets named stopwatch

# Build rule for target.
stopwatch: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stopwatch
.PHONY : stopwatch

# fast build rule for target.
stopwatch/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/stopwatch.dir/build.make examples/CMakeFiles/stopwatch.dir/build
.PHONY : stopwatch/fast

#=============================================================================
# Target rules for targets named template

# Build rule for target.
template: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 template
.PHONY : template

# fast build rule for target.
template/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/template.dir/build.make examples/CMakeFiles/template.dir/build
.PHONY : template/fast

#=============================================================================
# Target rules for targets named template_callbacks

# Build rule for target.
template_callbacks: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 template_callbacks
.PHONY : template_callbacks

# fast build rule for target.
template_callbacks/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/template_callbacks.dir/build.make examples/CMakeFiles/template_callbacks.dir/build
.PHONY : template_callbacks/fast

#=============================================================================
# Target rules for targets named time

# Build rule for target.
time: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 time
.PHONY : time

# fast build rule for target.
time/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/time.dir/build.make examples/CMakeFiles/time.dir/build
.PHONY : time/fast

#=============================================================================
# Target rules for targets named window

# Build rule for target.
window: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 window
.PHONY : window

# fast build rule for target.
window/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/window.dir/build.make examples/CMakeFiles/window.dir/build
.PHONY : window/fast

#=============================================================================
# Target rules for targets named test_tdd_stream

# Build rule for target.
test_tdd_stream: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_tdd_stream
.PHONY : test_tdd_stream

# fast build rule for target.
test_tdd_stream/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_tdd_stream.dir/build.make test/CMakeFiles/test_tdd_stream.dir/build
.PHONY : test_tdd_stream/fast

#=============================================================================
# Target rules for targets named test_unit_build_info

# Build rule for target.
test_unit_build_info: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_unit_build_info
.PHONY : test_unit_build_info

# fast build rule for target.
test_unit_build_info/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_unit_build_info.dir/build.make test/CMakeFiles/test_unit_build_info.dir/build
.PHONY : test_unit_build_info/fast

#=============================================================================
# Target rules for targets named test_unit_memory

# Build rule for target.
test_unit_memory: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_unit_memory
.PHONY : test_unit_memory

# fast build rule for target.
test_unit_memory/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_unit_memory.dir/build.make test/CMakeFiles/test_unit_memory.dir/build
.PHONY : test_unit_memory/fast

#=============================================================================
# Target rules for targets named test_unit_pixel

# Build rule for target.
test_unit_pixel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_unit_pixel
.PHONY : test_unit_pixel

# fast build rule for target.
test_unit_pixel/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_unit_pixel.dir/build.make test/CMakeFiles/test_unit_pixel.dir/build
.PHONY : test_unit_pixel/fast

#=============================================================================
# Target rules for targets named test_unit_rect

# Build rule for target.
test_unit_rect: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_unit_rect
.PHONY : test_unit_rect

# fast build rule for target.
test_unit_rect/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_unit_rect.dir/build.make test/CMakeFiles/test_unit_rect.dir/build
.PHONY : test_unit_rect/fast

#=============================================================================
# Target rules for targets named test_valid_bitmap

# Build rule for target.
test_valid_bitmap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_valid_bitmap
.PHONY : test_valid_bitmap

# fast build rule for target.
test_valid_bitmap/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_valid_bitmap.dir/build.make test/CMakeFiles/test_valid_bitmap.dir/build
.PHONY : test_valid_bitmap/fast

src/api.o: src/api.c.o
.PHONY : src/api.o

# target to build an object file
src/api.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/api.c.o
.PHONY : src/api.c.o

src/api.i: src/api.c.i
.PHONY : src/api.i

# target to preprocess a source file
src/api.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/api.c.i
.PHONY : src/api.c.i

src/api.s: src/api.c.s
.PHONY : src/api.s

# target to generate assembly for a file
src/api.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/api.c.s
.PHONY : src/api.c.s

src/audio.o: src/audio.c.o
.PHONY : src/audio.o

# target to build an object file
src/audio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/audio.c.o
.PHONY : src/audio.c.o

src/audio.i: src/audio.c.i
.PHONY : src/audio.i

# target to preprocess a source file
src/audio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/audio.c.i
.PHONY : src/audio.c.i

src/audio.s: src/audio.c.s
.PHONY : src/audio.s

# target to generate assembly for a file
src/audio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/audio.c.s
.PHONY : src/audio.c.s

src/audio_alsa.o: src/audio_alsa.c.o
.PHONY : src/audio_alsa.o

# target to build an object file
src/audio_alsa.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/audio_alsa.c.o
.PHONY : src/audio_alsa.c.o

src/audio_alsa.i: src/audio_alsa.c.i
.PHONY : src/audio_alsa.i

# target to preprocess a source file
src/audio_alsa.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/audio_alsa.c.i
.PHONY : src/audio_alsa.c.i

src/audio_alsa.s: src/audio_alsa.c.s
.PHONY : src/audio_alsa.s

# target to generate assembly for a file
src/audio_alsa.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/audio_alsa.c.s
.PHONY : src/audio_alsa.c.s

src/audio_emscripten.o: src/audio_emscripten.c.o
.PHONY : src/audio_emscripten.o

# target to build an object file
src/audio_emscripten.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/audio_emscripten.c.o
.PHONY : src/audio_emscripten.c.o

src/audio_emscripten.i: src/audio_emscripten.c.i
.PHONY : src/audio_emscripten.i

# target to preprocess a source file
src/audio_emscripten.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/audio_emscripten.c.i
.PHONY : src/audio_emscripten.c.i

src/audio_emscripten.s: src/audio_emscripten.c.s
.PHONY : src/audio_emscripten.s

# target to generate assembly for a file
src/audio_emscripten.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/audio_emscripten.c.s
.PHONY : src/audio_emscripten.c.s

src/audio_mme.o: src/audio_mme.c.o
.PHONY : src/audio_mme.o

# target to build an object file
src/audio_mme.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/audio_mme.c.o
.PHONY : src/audio_mme.c.o

src/audio_mme.i: src/audio_mme.c.i
.PHONY : src/audio_mme.i

# target to preprocess a source file
src/audio_mme.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/audio_mme.c.i
.PHONY : src/audio_mme.c.i

src/audio_mme.s: src/audio_mme.c.s
.PHONY : src/audio_mme.s

# target to generate assembly for a file
src/audio_mme.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/audio_mme.c.s
.PHONY : src/audio_mme.c.s

src/bitmap.o: src/bitmap.c.o
.PHONY : src/bitmap.o

# target to build an object file
src/bitmap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/bitmap.c.o
.PHONY : src/bitmap.c.o

src/bitmap.i: src/bitmap.c.i
.PHONY : src/bitmap.i

# target to preprocess a source file
src/bitmap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/bitmap.c.i
.PHONY : src/bitmap.c.i

src/bitmap.s: src/bitmap.c.s
.PHONY : src/bitmap.s

# target to generate assembly for a file
src/bitmap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/bitmap.c.s
.PHONY : src/bitmap.c.s

src/bitmap_blit.o: src/bitmap_blit.c.o
.PHONY : src/bitmap_blit.o

# target to build an object file
src/bitmap_blit.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/bitmap_blit.c.o
.PHONY : src/bitmap_blit.c.o

src/bitmap_blit.i: src/bitmap_blit.c.i
.PHONY : src/bitmap_blit.i

# target to preprocess a source file
src/bitmap_blit.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/bitmap_blit.c.i
.PHONY : src/bitmap_blit.c.i

src/bitmap_blit.s: src/bitmap_blit.c.s
.PHONY : src/bitmap_blit.s

# target to generate assembly for a file
src/bitmap_blit.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/bitmap_blit.c.s
.PHONY : src/bitmap_blit.c.s

src/bitmap_blit_mask.o: src/bitmap_blit_mask.c.o
.PHONY : src/bitmap_blit_mask.o

# target to build an object file
src/bitmap_blit_mask.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/bitmap_blit_mask.c.o
.PHONY : src/bitmap_blit_mask.c.o

src/bitmap_blit_mask.i: src/bitmap_blit_mask.c.i
.PHONY : src/bitmap_blit_mask.i

# target to preprocess a source file
src/bitmap_blit_mask.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/bitmap_blit_mask.c.i
.PHONY : src/bitmap_blit_mask.c.i

src/bitmap_blit_mask.s: src/bitmap_blit_mask.c.s
.PHONY : src/bitmap_blit_mask.s

# target to generate assembly for a file
src/bitmap_blit_mask.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/bitmap_blit_mask.c.s
.PHONY : src/bitmap_blit_mask.c.s

src/bitmap_dib.o: src/bitmap_dib.c.o
.PHONY : src/bitmap_dib.o

# target to build an object file
src/bitmap_dib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/bitmap_dib.c.o
.PHONY : src/bitmap_dib.c.o

src/bitmap_dib.i: src/bitmap_dib.c.i
.PHONY : src/bitmap_dib.i

# target to preprocess a source file
src/bitmap_dib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/bitmap_dib.c.i
.PHONY : src/bitmap_dib.c.i

src/bitmap_dib.s: src/bitmap_dib.c.s
.PHONY : src/bitmap_dib.s

# target to generate assembly for a file
src/bitmap_dib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/bitmap_dib.c.s
.PHONY : src/bitmap_dib.c.s

src/bitmap_draw.o: src/bitmap_draw.c.o
.PHONY : src/bitmap_draw.o

# target to build an object file
src/bitmap_draw.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/bitmap_draw.c.o
.PHONY : src/bitmap_draw.c.o

src/bitmap_draw.i: src/bitmap_draw.c.i
.PHONY : src/bitmap_draw.i

# target to preprocess a source file
src/bitmap_draw.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/bitmap_draw.c.i
.PHONY : src/bitmap_draw.c.i

src/bitmap_draw.s: src/bitmap_draw.c.s
.PHONY : src/bitmap_draw.s

# target to generate assembly for a file
src/bitmap_draw.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/bitmap_draw.c.s
.PHONY : src/bitmap_draw.c.s

src/bitmap_text.o: src/bitmap_text.c.o
.PHONY : src/bitmap_text.o

# target to build an object file
src/bitmap_text.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/bitmap_text.c.o
.PHONY : src/bitmap_text.c.o

src/bitmap_text.i: src/bitmap_text.c.i
.PHONY : src/bitmap_text.i

# target to preprocess a source file
src/bitmap_text.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/bitmap_text.c.i
.PHONY : src/bitmap_text.c.i

src/bitmap_text.s: src/bitmap_text.c.s
.PHONY : src/bitmap_text.s

# target to generate assembly for a file
src/bitmap_text.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/bitmap_text.c.s
.PHONY : src/bitmap_text.c.s

src/error.o: src/error.c.o
.PHONY : src/error.o

# target to build an object file
src/error.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/error.c.o
.PHONY : src/error.c.o

src/error.i: src/error.c.i
.PHONY : src/error.i

# target to preprocess a source file
src/error.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/error.c.i
.PHONY : src/error.c.i

src/error.s: src/error.c.s
.PHONY : src/error.s

# target to generate assembly for a file
src/error.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/error.c.s
.PHONY : src/error.c.s

src/event.o: src/event.c.o
.PHONY : src/event.o

# target to build an object file
src/event.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/event.c.o
.PHONY : src/event.c.o

src/event.i: src/event.c.i
.PHONY : src/event.i

# target to preprocess a source file
src/event.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/event.c.i
.PHONY : src/event.c.i

src/event.s: src/event.c.s
.PHONY : src/event.s

# target to generate assembly for a file
src/event.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/event.c.s
.PHONY : src/event.c.s

src/log.o: src/log.c.o
.PHONY : src/log.o

# target to build an object file
src/log.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/log.c.o
.PHONY : src/log.c.o

src/log.i: src/log.c.i
.PHONY : src/log.i

# target to preprocess a source file
src/log.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/log.c.i
.PHONY : src/log.c.i

src/log.s: src/log.c.s
.PHONY : src/log.s

# target to generate assembly for a file
src/log.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/log.c.s
.PHONY : src/log.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/main.c.s
.PHONY : src/main.c.s

src/main_callbacks.o: src/main_callbacks.c.o
.PHONY : src/main_callbacks.o

# target to build an object file
src/main_callbacks.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/main_callbacks.c.o
.PHONY : src/main_callbacks.c.o

src/main_callbacks.i: src/main_callbacks.c.i
.PHONY : src/main_callbacks.i

# target to preprocess a source file
src/main_callbacks.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/main_callbacks.c.i
.PHONY : src/main_callbacks.c.i

src/main_callbacks.s: src/main_callbacks.c.s
.PHONY : src/main_callbacks.s

# target to generate assembly for a file
src/main_callbacks.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/main_callbacks.c.s
.PHONY : src/main_callbacks.c.s

src/memory.o: src/memory.c.o
.PHONY : src/memory.o

# target to build an object file
src/memory.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/memory.c.o
.PHONY : src/memory.c.o

src/memory.i: src/memory.c.i
.PHONY : src/memory.i

# target to preprocess a source file
src/memory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/memory.c.i
.PHONY : src/memory.c.i

src/memory.s: src/memory.c.s
.PHONY : src/memory.s

# target to generate assembly for a file
src/memory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/memory.c.s
.PHONY : src/memory.c.s

src/noaudio.o: src/noaudio.c.o
.PHONY : src/noaudio.o

# target to build an object file
src/noaudio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/noaudio.c.o
.PHONY : src/noaudio.c.o

src/noaudio.i: src/noaudio.c.i
.PHONY : src/noaudio.i

# target to preprocess a source file
src/noaudio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/noaudio.c.i
.PHONY : src/noaudio.c.i

src/noaudio.s: src/noaudio.c.s
.PHONY : src/noaudio.s

# target to generate assembly for a file
src/noaudio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/noaudio.c.s
.PHONY : src/noaudio.c.s

src/novideo.o: src/novideo.c.o
.PHONY : src/novideo.o

# target to build an object file
src/novideo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/novideo.c.o
.PHONY : src/novideo.c.o

src/novideo.i: src/novideo.c.i
.PHONY : src/novideo.i

# target to preprocess a source file
src/novideo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/novideo.c.i
.PHONY : src/novideo.c.i

src/novideo.s: src/novideo.c.s
.PHONY : src/novideo.s

# target to generate assembly for a file
src/novideo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/novideo.c.s
.PHONY : src/novideo.c.s

src/pixel.o: src/pixel.c.o
.PHONY : src/pixel.o

# target to build an object file
src/pixel.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/pixel.c.o
.PHONY : src/pixel.c.o

src/pixel.i: src/pixel.c.i
.PHONY : src/pixel.i

# target to preprocess a source file
src/pixel.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/pixel.c.i
.PHONY : src/pixel.c.i

src/pixel.s: src/pixel.c.s
.PHONY : src/pixel.s

# target to generate assembly for a file
src/pixel.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/pixel.c.s
.PHONY : src/pixel.c.s

src/rect.o: src/rect.c.o
.PHONY : src/rect.o

# target to build an object file
src/rect.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/rect.c.o
.PHONY : src/rect.c.o

src/rect.i: src/rect.c.i
.PHONY : src/rect.i

# target to preprocess a source file
src/rect.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/rect.c.i
.PHONY : src/rect.c.i

src/rect.s: src/rect.c.s
.PHONY : src/rect.s

# target to generate assembly for a file
src/rect.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/rect.c.s
.PHONY : src/rect.c.s

src/shader.o: src/shader.c.o
.PHONY : src/shader.o

# target to build an object file
src/shader.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/shader.c.o
.PHONY : src/shader.c.o

src/shader.i: src/shader.c.i
.PHONY : src/shader.i

# target to preprocess a source file
src/shader.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/shader.c.i
.PHONY : src/shader.c.i

src/shader.s: src/shader.c.s
.PHONY : src/shader.s

# target to generate assembly for a file
src/shader.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/shader.c.s
.PHONY : src/shader.c.s

src/stream.o: src/stream.c.o
.PHONY : src/stream.o

# target to build an object file
src/stream.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/stream.c.o
.PHONY : src/stream.c.o

src/stream.i: src/stream.c.i
.PHONY : src/stream.i

# target to preprocess a source file
src/stream.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/stream.c.i
.PHONY : src/stream.c.i

src/stream.s: src/stream.c.s
.PHONY : src/stream.s

# target to generate assembly for a file
src/stream.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/stream.c.s
.PHONY : src/stream.c.s

src/system.o: src/system.c.o
.PHONY : src/system.o

# target to build an object file
src/system.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/system.c.o
.PHONY : src/system.c.o

src/system.i: src/system.c.i
.PHONY : src/system.i

# target to preprocess a source file
src/system.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/system.c.i
.PHONY : src/system.c.i

src/system.s: src/system.c.s
.PHONY : src/system.s

# target to generate assembly for a file
src/system.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/system.c.s
.PHONY : src/system.c.s

src/system_unix.o: src/system_unix.c.o
.PHONY : src/system_unix.o

# target to build an object file
src/system_unix.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/system_unix.c.o
.PHONY : src/system_unix.c.o

src/system_unix.i: src/system_unix.c.i
.PHONY : src/system_unix.i

# target to preprocess a source file
src/system_unix.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/system_unix.c.i
.PHONY : src/system_unix.c.i

src/system_unix.s: src/system_unix.c.s
.PHONY : src/system_unix.s

# target to generate assembly for a file
src/system_unix.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/system_unix.c.s
.PHONY : src/system_unix.c.s

src/system_win32.o: src/system_win32.c.o
.PHONY : src/system_win32.o

# target to build an object file
src/system_win32.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/system_win32.c.o
.PHONY : src/system_win32.c.o

src/system_win32.i: src/system_win32.c.i
.PHONY : src/system_win32.i

# target to preprocess a source file
src/system_win32.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/system_win32.c.i
.PHONY : src/system_win32.c.i

src/system_win32.s: src/system_win32.c.s
.PHONY : src/system_win32.s

# target to generate assembly for a file
src/system_win32.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/system_win32.c.s
.PHONY : src/system_win32.c.s

src/time.o: src/time.c.o
.PHONY : src/time.o

# target to build an object file
src/time.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/time.c.o
.PHONY : src/time.c.o

src/time.i: src/time.c.i
.PHONY : src/time.i

# target to preprocess a source file
src/time.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/time.c.i
.PHONY : src/time.c.i

src/time.s: src/time.c.s
.PHONY : src/time.s

# target to generate assembly for a file
src/time.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/time.c.s
.PHONY : src/time.c.s

src/time_unix.o: src/time_unix.c.o
.PHONY : src/time_unix.o

# target to build an object file
src/time_unix.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/time_unix.c.o
.PHONY : src/time_unix.c.o

src/time_unix.i: src/time_unix.c.i
.PHONY : src/time_unix.i

# target to preprocess a source file
src/time_unix.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/time_unix.c.i
.PHONY : src/time_unix.c.i

src/time_unix.s: src/time_unix.c.s
.PHONY : src/time_unix.s

# target to generate assembly for a file
src/time_unix.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/time_unix.c.s
.PHONY : src/time_unix.c.s

src/time_win32.o: src/time_win32.c.o
.PHONY : src/time_win32.o

# target to build an object file
src/time_win32.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/time_win32.c.o
.PHONY : src/time_win32.c.o

src/time_win32.i: src/time_win32.c.i
.PHONY : src/time_win32.i

# target to preprocess a source file
src/time_win32.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/time_win32.c.i
.PHONY : src/time_win32.c.i

src/time_win32.s: src/time_win32.c.s
.PHONY : src/time_win32.s

# target to generate assembly for a file
src/time_win32.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/time_win32.c.s
.PHONY : src/time_win32.c.s

src/video.o: src/video.c.o
.PHONY : src/video.o

# target to build an object file
src/video.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/video.c.o
.PHONY : src/video.c.o

src/video.i: src/video.c.i
.PHONY : src/video.i

# target to preprocess a source file
src/video.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/video.c.i
.PHONY : src/video.c.i

src/video.s: src/video.c.s
.PHONY : src/video.s

# target to generate assembly for a file
src/video.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/video.c.s
.PHONY : src/video.c.s

src/video_emscripten.o: src/video_emscripten.c.o
.PHONY : src/video_emscripten.o

# target to build an object file
src/video_emscripten.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/video_emscripten.c.o
.PHONY : src/video_emscripten.c.o

src/video_emscripten.i: src/video_emscripten.c.i
.PHONY : src/video_emscripten.i

# target to preprocess a source file
src/video_emscripten.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/video_emscripten.c.i
.PHONY : src/video_emscripten.c.i

src/video_emscripten.s: src/video_emscripten.c.s
.PHONY : src/video_emscripten.s

# target to generate assembly for a file
src/video_emscripten.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/video_emscripten.c.s
.PHONY : src/video_emscripten.c.s

src/video_win32.o: src/video_win32.c.o
.PHONY : src/video_win32.o

# target to build an object file
src/video_win32.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/video_win32.c.o
.PHONY : src/video_win32.c.o

src/video_win32.i: src/video_win32.c.i
.PHONY : src/video_win32.i

# target to preprocess a source file
src/video_win32.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/video_win32.c.i
.PHONY : src/video_win32.c.i

src/video_win32.s: src/video_win32.c.s
.PHONY : src/video_win32.s

# target to generate assembly for a file
src/video_win32.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/video_win32.c.s
.PHONY : src/video_win32.c.s

src/video_x11.o: src/video_x11.c.o
.PHONY : src/video_x11.o

# target to build an object file
src/video_x11.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/video_x11.c.o
.PHONY : src/video_x11.c.o

src/video_x11.i: src/video_x11.c.i
.PHONY : src/video_x11.i

# target to preprocess a source file
src/video_x11.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/video_x11.c.i
.PHONY : src/video_x11.c.i

src/video_x11.s: src/video_x11.c.s
.PHONY : src/video_x11.s

# target to generate assembly for a file
src/video_x11.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/video_x11.c.s
.PHONY : src/video_x11.c.s

src/window.o: src/window.c.o
.PHONY : src/window.o

# target to build an object file
src/window.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/window.c.o
.PHONY : src/window.c.o

src/window.i: src/window.c.i
.PHONY : src/window.i

# target to preprocess a source file
src/window.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/window.c.i
.PHONY : src/window.c.i

src/window.s: src/window.c.s
.PHONY : src/window.s

# target to generate assembly for a file
src/window.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/banjo.dir/build.make CMakeFiles/banjo.dir/src/window.c.s
.PHONY : src/window.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... assert"
	@echo "... audio_pcm"
	@echo "... banjo"
	@echo "... bitmap_blit"
	@echo "... build_info"
	@echo "... drawing_2d"
	@echo "... drawing_text"
	@echo "... event_callbacks"
	@echo "... event_polling"
	@echo "... handling_errors"
	@echo "... load_bmp"
	@echo "... logging"
	@echo "... memory_callbacks"
	@echo "... pixel_mode"
	@echo "... shaders"
	@echo "... sprite_animation"
	@echo "... stopwatch"
	@echo "... template"
	@echo "... template_callbacks"
	@echo "... test_tdd_stream"
	@echo "... test_unit_build_info"
	@echo "... test_unit_memory"
	@echo "... test_unit_pixel"
	@echo "... test_unit_rect"
	@echo "... test_valid_bitmap"
	@echo "... time"
	@echo "... window"
	@echo "... src/api.o"
	@echo "... src/api.i"
	@echo "... src/api.s"
	@echo "... src/audio.o"
	@echo "... src/audio.i"
	@echo "... src/audio.s"
	@echo "... src/audio_alsa.o"
	@echo "... src/audio_alsa.i"
	@echo "... src/audio_alsa.s"
	@echo "... src/audio_emscripten.o"
	@echo "... src/audio_emscripten.i"
	@echo "... src/audio_emscripten.s"
	@echo "... src/audio_mme.o"
	@echo "... src/audio_mme.i"
	@echo "... src/audio_mme.s"
	@echo "... src/bitmap.o"
	@echo "... src/bitmap.i"
	@echo "... src/bitmap.s"
	@echo "... src/bitmap_blit.o"
	@echo "... src/bitmap_blit.i"
	@echo "... src/bitmap_blit.s"
	@echo "... src/bitmap_blit_mask.o"
	@echo "... src/bitmap_blit_mask.i"
	@echo "... src/bitmap_blit_mask.s"
	@echo "... src/bitmap_dib.o"
	@echo "... src/bitmap_dib.i"
	@echo "... src/bitmap_dib.s"
	@echo "... src/bitmap_draw.o"
	@echo "... src/bitmap_draw.i"
	@echo "... src/bitmap_draw.s"
	@echo "... src/bitmap_text.o"
	@echo "... src/bitmap_text.i"
	@echo "... src/bitmap_text.s"
	@echo "... src/error.o"
	@echo "... src/error.i"
	@echo "... src/error.s"
	@echo "... src/event.o"
	@echo "... src/event.i"
	@echo "... src/event.s"
	@echo "... src/log.o"
	@echo "... src/log.i"
	@echo "... src/log.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/main_callbacks.o"
	@echo "... src/main_callbacks.i"
	@echo "... src/main_callbacks.s"
	@echo "... src/memory.o"
	@echo "... src/memory.i"
	@echo "... src/memory.s"
	@echo "... src/noaudio.o"
	@echo "... src/noaudio.i"
	@echo "... src/noaudio.s"
	@echo "... src/novideo.o"
	@echo "... src/novideo.i"
	@echo "... src/novideo.s"
	@echo "... src/pixel.o"
	@echo "... src/pixel.i"
	@echo "... src/pixel.s"
	@echo "... src/rect.o"
	@echo "... src/rect.i"
	@echo "... src/rect.s"
	@echo "... src/shader.o"
	@echo "... src/shader.i"
	@echo "... src/shader.s"
	@echo "... src/stream.o"
	@echo "... src/stream.i"
	@echo "... src/stream.s"
	@echo "... src/system.o"
	@echo "... src/system.i"
	@echo "... src/system.s"
	@echo "... src/system_unix.o"
	@echo "... src/system_unix.i"
	@echo "... src/system_unix.s"
	@echo "... src/system_win32.o"
	@echo "... src/system_win32.i"
	@echo "... src/system_win32.s"
	@echo "... src/time.o"
	@echo "... src/time.i"
	@echo "... src/time.s"
	@echo "... src/time_unix.o"
	@echo "... src/time_unix.i"
	@echo "... src/time_unix.s"
	@echo "... src/time_win32.o"
	@echo "... src/time_win32.i"
	@echo "... src/time_win32.s"
	@echo "... src/video.o"
	@echo "... src/video.i"
	@echo "... src/video.s"
	@echo "... src/video_emscripten.o"
	@echo "... src/video_emscripten.i"
	@echo "... src/video_emscripten.s"
	@echo "... src/video_win32.o"
	@echo "... src/video_win32.i"
	@echo "... src/video_win32.s"
	@echo "... src/video_x11.o"
	@echo "... src/video_x11.i"
	@echo "... src/video_x11.s"
	@echo "... src/window.o"
	@echo "... src/window.i"
	@echo "... src/window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/oragon/ws/banjo/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

