#include <banjo/input.h>

const char* bj_get_key_name(int key) {
    switch(key) {
        case BJ_KEY_SPACE: return "Space";
        case BJ_KEY_APOSTROPHE: return "\"";
        case BJ_KEY_COMMA: return ",";
        case BJ_KEY_MINUS: return "-";
        case BJ_KEY_PERIOD: return ".";
        case BJ_KEY_SLASH: return "/";
        case BJ_KEY_0: return "0";
        case BJ_KEY_1: return "1";
        case BJ_KEY_2: return "2";
        case BJ_KEY_3: return "3";
        case BJ_KEY_4: return "4";
        case BJ_KEY_5: return "5";
        case BJ_KEY_6: return "6";
        case BJ_KEY_7: return "7";
        case BJ_KEY_8: return "8";
        case BJ_KEY_9: return "9";
        case BJ_KEY_A: return "A";
        case BJ_KEY_B: return "B";
        case BJ_KEY_C: return "C";
        case BJ_KEY_D: return "D";
        case BJ_KEY_E: return "E";
        case BJ_KEY_F: return "F";
        case BJ_KEY_G: return "G";
        case BJ_KEY_H: return "H";
        case BJ_KEY_I: return "I";
        case BJ_KEY_J: return "J";
        case BJ_KEY_K: return "K";
        case BJ_KEY_L: return "L";
        case BJ_KEY_M: return "M";
        case BJ_KEY_N: return "N";
        case BJ_KEY_O: return "O";
        case BJ_KEY_P: return "P";
        case BJ_KEY_Q: return "Q";
        case BJ_KEY_R: return "R";
        case BJ_KEY_S: return "S";
        case BJ_KEY_T: return "T";
        case BJ_KEY_U: return "U";
        case BJ_KEY_V: return "V";
        case BJ_KEY_W: return "W";
        case BJ_KEY_X: return "X";
        case BJ_KEY_Y: return "Y";
        case BJ_KEY_Z: return "Z";
        case BJ_KEY_SEMICOLON: return ";";
        case BJ_KEY_EQUAL: return "=";
        case BJ_KEY_LEFT_BRACKET: return "[";
        case BJ_KEY_BACKSLASH: return "\\";
        case BJ_KEY_RIGHT_BRACKET: return "]";
        case BJ_KEY_GRAVE_ACCENT: return "`";
        case BJ_KEY_ESCAPE: return "Esc";
        case BJ_KEY_RETURN: return "Return";
        case BJ_KEY_TAB: return "Tab";
        case BJ_KEY_BACKSPACE: return "Backspace";
        case BJ_KEY_INSERT: return "Insert";
        case BJ_KEY_DELETE: return "Delete";
        case BJ_KEY_LEFT: return "Left";
        case BJ_KEY_UP: return "Up";
        case BJ_KEY_RIGHT: return "Right";
        case BJ_KEY_DOWN: return "Down";
        case BJ_KEY_PRIOR: return "Page Up";
        case BJ_KEY_NEXT: return "Page Down";
        case BJ_KEY_HOME: return "Home";
        case BJ_KEY_END: return "End";
        case BJ_KEY_CAPSLOCK: return "CAPS Lock";
        case BJ_KEY_SCROLL: return "Scroll Lock";
        case BJ_KEY_NUMLOCK: return "Num Lock";
        case BJ_KEY_PRINTSCREEN: return "Print Screen";
        case BJ_KEY_PAUSE: return "Pause";
        case BJ_KEY_F1: return "F1";
        case BJ_KEY_F2: return "F2";
        case BJ_KEY_F3: return "F3";
        case BJ_KEY_F4: return "F4";
        case BJ_KEY_F5: return "F5";
        case BJ_KEY_F6: return "F6";
        case BJ_KEY_F7: return "F7";
        case BJ_KEY_F8: return "F8";
        case BJ_KEY_F9: return "F9";
        case BJ_KEY_F10: return "F10";
        case BJ_KEY_F11: return "F11";
        case BJ_KEY_F12: return "F12";
        case BJ_KEY_F13: return "F13";
        case BJ_KEY_F14: return "F14";
        case BJ_KEY_F15: return "F15";
        case BJ_KEY_F16: return "F16";
        case BJ_KEY_F17: return "F17";
        case BJ_KEY_F18: return "F18";
        case BJ_KEY_F19: return "F19";
        case BJ_KEY_F20: return "F20";
        case BJ_KEY_F21: return "F21";
        case BJ_KEY_F22: return "F22";
        case BJ_KEY_F23: return "F23";
        case BJ_KEY_F24: return "F24";
        case BJ_KEY_PAD_0: return "Numpad 0";
        case BJ_KEY_PAD_1: return "Numpad 1";
        case BJ_KEY_PAD_2: return "Numpad 2";
        case BJ_KEY_PAD_3: return "Numpad 3";
        case BJ_KEY_PAD_4: return "Numpad 4";
        case BJ_KEY_PAD_5: return "Numpad 5";
        case BJ_KEY_PAD_6: return "Numpad 6";
        case BJ_KEY_PAD_7: return "Numpad 7";
        case BJ_KEY_PAD_8: return "Numpad 8";
        case BJ_KEY_PAD_9: return "Numpad 9";
        case BJ_KEY_PAD_DECIMAL: return "Numpad .";
        case BJ_KEY_PAD_DIVIDE: return "Numpad /";
        case BJ_KEY_PAD_MULTIPLY: return "Numpad *";
        case BJ_KEY_PAD_SUBTRACT: return "Numpad -";
        case BJ_KEY_PAD_ADD: return "Numpad +";
        case BJ_KEY_SHIFT_LEFT: return "Left Shift";
        case BJ_KEY_SHIFT_RIGHT: return "Right Shift";
        case BJ_KEY_CONTROL_LEFT: return "Left CTRL";
        case BJ_KEY_CONTROL_RIGHT: return "Right CTRL";
        case BJ_KEY_ALT_LEFT: return "Left ALT";
        case BJ_KEY_ALT_RIGHT: return "Right ALT";
        case BJ_KEY_OS_LEFT: return "Left SYS";
        case BJ_KEY_OS_RIGHT: return "Right SYS";
    }
    return "Unknown";
}