name: Build/Windows/MSVC

on:
  push:
    branches: [win_ci]
  pull_request:
    branches: [win_ci]

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        config: [debug, release]
        type: [shared, static]
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set environment variables
      run: |
        echo CONFIG=${{ matrix.config }} >> $GITHUB_ENV
        echo TYPE=${{ matrix.type }} >> $GITHUB_ENV

    - name: Run Make.bat with VS environment
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
        call Make.bat
