name: Build/Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        config: [release]
        type: [shared, static]
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Configure (MSVC)
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64

    - name: Configure (Env)
      run: |
        echo CONFIG=${{ matrix.config }} >> $GITHUB_ENV
        echo TYPE=${{ matrix.type }} >> $GITHUB_ENV

    - name: Build
      shell: cmd
      run: |
        call Make.bat

    - name: Test
      shell: cmd
      run: |
        call Make.bat test
