name: Build/Windows/MSVC

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests targeting the main branch

jobs:
  build:
    runs-on: windows-latest  # Use the latest Windows runner
    
    strategy:
      matrix:
        config: [debug, release]  # Matrix for the CONFIG variable
        type: [shared, static]    # Matrix for the TYPE variable
      fail-fast: false  # Optionally set fail-fast to false if you want to run all combinations even if one fails
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository

    - name: Set up Visual Studio 2022 Build Tools
      uses: microsoft/setup-msbuild@v1.0.2  # Set up MSBuild with Visual Studio 2022

    - name: Set environment variables
      run: |
        echo "CONFIG=${{ matrix.config }}" >> $GITHUB_ENV
        echo "TYPE=${{ matrix.type }}" >> $GITHUB_ENV

    - name: Run Make.bat
      run: |
        echo "Building with CONFIG=${{ matrix.config }} and TYPE=${{ matrix.type }}"
        ./Make.bat  # Run your custom Make.bat script
